### ISSUE TITLE
the pkl data

### ISSUE THREAD

**Issue by jiaodu12138** [means-to-meaning/easy21#2]
How is the data set in the result folder generated?
Shouldn't it be generated by your code?
Coule you please introduce the structure and content of the data set? I don't understand.

**Comment by means-to-meaning** [comment]
The result files are generated here (for the case of SARSA): https://github.com/means-to-meaning/easy21/blob/master/sarsa.py#L105
With regard to content - it's a dictionary containing the past states and rewards, see code above for details.
